=== abstractiondev/DemoSOCase8552428ABS/DemoSOCase8552428/Content_v1_0/ImportXml.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2011 rel. 2 sp1 (http://www.altova.com) by Kalle Launiala (Citrus Solutions Oy) -->
<!--W3C Schema generated by XMLSpy v2011 rel. 2 sp1 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="GeneratedSolution" type="GeneratedSolutionType"/>
	<xs:complexType name="GeneratedSolutionType">
		<xs:sequence>
			<xs:element name="GeneratedProject" type="GeneratedProjectType" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="Name" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="name of Solution"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="GeneratedProjectType">
		<xs:choice>
			<xs:element name="GeneratedBusiness" type="GeneratedBusinessType"/>
			<xs:element name="GeneratedUI" type="GeneratedUIType"/>
			<xs:sequence>
				<xs:element name="Compiler" type="CompilerType"/>
				<xs:element name="GeneratedRepository" type="GeneratedRepositoryType"/>
			</xs:sequence>
		</xs:choice>
		<xs:attribute name="OutExtension">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="cs"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="Name" type="xs:string" use="required"/>
		<xs:attribute name="MinorVersion" type="xs:int" use="required"/>
		<xs:attribute name="MajorVersion" type="xs:int" use="required"/>
		<xs:attribute name="Language">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="C#"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="ID" type="xs:string" use="required"/>
		<xs:attribute name="CopyRight" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="GeneratedBusinessType">
		<xs:sequence>
			<xs:element name="Operation" type="OperationType" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="TemplateRefence" type="xs:string" use="required"/>
		<xs:attribute name="Name" type="xs:string" use="required"/>
		<xs:attribute name="Description" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="OperationType">
		<xs:sequence>
			<xs:element name="operationID" type="xs:int"/>
		</xs:sequence>
		<xs:attribute name="Name" type="xs:string" use="required"/>
		<xs:attribute name="Description" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="GeneratedUIType">
		<xs:sequence>
			<xs:element name="Operation" type="OperationType" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="TemplateRefence" type="xs:string" use="required"/>
		<xs:attribute name="Name" type="xs:string" use="required"/>
		<xs:attribute name="Description" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="CompilerType">
		<xs:attribute name="path" type="xs:string" use="required"/>
		<xs:attribute name="ExternalBuildTool" type="xs:string" use="required"/>
		<xs:attribute name="Build" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="GeneratedRepositoryType">
		<xs:sequence>
			<xs:element name="Operation" type="OperationType" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="TemplateRefence" type="xs:string" use="required"/>
		<xs:attribute name="Name" type="xs:string" use="required"/>
		<xs:attribute name="Description" type="xs:string" use="required"/>
	</xs:complexType>
</xs:schema>

=== abstractiondev/DemoSOCase8552428ABS/DemoSOCase8552428/Content_v1_0/ImportXml.xml
<?xml version="1.0" encoding="utf-8"?>
<GeneratedSolution Name="name of Solution" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ImportXml.xsd">
	<GeneratedProject ID="RepoProject" Name="name of Project" MajorVersion="1" MinorVersion="0" CopyRight="GeneratedProject company" Language="C#" OutExtension="cs">
		<Compiler path="../path/compilername" Build="silent" ExternalBuildTool="NAnt"/>
		<GeneratedRepository Name="name of Repository Class" Description="This is generated Repository class would be used for overall-application" TemplateRefence="../path/repository.tt">
			<Operation Name="Operation1" Description="This is operation1 of Repository class">
				<operationID>1</operationID>
			</Operation>
			<Operation Name="Operation2" Description="This is operation2 of Repository class">
				<operationID>2</operationID>
			</Operation>
		</GeneratedRepository>
	</GeneratedProject>
	<GeneratedProject ID="BusinessProject" Name="name of Project" MajorVersion="1" MinorVersion="0" CopyRight="GeneratedProject company">
		<GeneratedBusiness Name="name of Business Class" Description="This is generated Business class would be used for overall-application" TemplateRefence="../path/business.tt">
			<Operation Name="Operation1" Description="This is operation1 of Business class">
				<operationID>1</operationID>
			</Operation>
			<Operation Name="Operation2" Description="This is operation2 of Business class">
				<operationID>2</operationID>
			</Operation>
		</GeneratedBusiness>
	</GeneratedProject>
	<GeneratedProject ID="UIProject" Name="name of Project" MajorVersion="1" MinorVersion="0" CopyRight="GeneratedProject company">
		<GeneratedUI Name="name of UI Class" Description="This is generated UI class would be used for overall-application" TemplateRefence="../path/UI.tt">
			<Operation Name="Operation1" Description="This is operation1 of UI class">
				<operationID>1</operationID>
			</Operation>
			<Operation Name="Operation2" Description="This is operation2 of UI class">
				<operationID>2</operationID>
			</Operation>
		</GeneratedUI>
	</GeneratedProject>
</GeneratedSolution>
